name: Build
on:
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    strategy:
      matrix:
        variant: [gcc, lto, server, hardened, lts, rc]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - run: nix build .#linux_cachyos-${{ matrix.variant }} -L
