name: Build and Push Nix Cache

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            accept-flake-config = true
            sandbox-fallback = false
            access-tokens = github.com=${{ secrets.GH_TOKEN }}

      - name: Setup Cachix
        uses: cachix/cachix-action@v16
        with:
          name: loneros
          extraPullNames: nix-community

      - name: Install noci
        run: nix profile install github:lonerOrz/noci

      - name: Build and Push Cache
        env:
          NOCI_REPO: ${{ github.repository_owner }}/cachyos-loner
          NOCI_SIGNING_KEY: ${{ secrets.NOCI_SIGNING_KEY }}
          NOCI_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          noci push .#linux_cachyos-gcc

      - name: Run Garbage Collection
        env:
          NOCI_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          noci gc --max-size 5GB --grace-period 6h --dry-run=false
