name: Bump
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
jobs:
  bump:
    strategy:
      matrix:
        variant: [gcc, lto, server, hardened, rc, lts]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v30
      - run: git config user.name "cachyos-loner[bot]"
      - run: git config user.email "cachyos-loner[bot]@users.noreply.github.com"
      - run: nix run ".#linux_cachyos-${{ matrix.variant }}.passthru.updateScript" --impure
      - run: nix eval ".#linux_cachyos-${{ matrix.variant }}.version" --impure -L
