name: Check
on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  check:
    strategy:
      matrix:
        variant: [gcc, lto, lto-znver4, server, hardened, lts, rc]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-build
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          noci-signing-key: ${{ secrets.NOCI_SIGNING_KEY }}

      - name: Verify Kernel Configuration and Patches
        run: nix build .#linux_cachyos-${{ matrix.variant }}.configfile -L --impure

  config-nix-check:
    strategy:
      matrix:
        include:
          - variant: gcc
            config_file: cachyos-gcc.x86_64-linux.nix
          - variant: lto
            config_file: cachyos-lto.x86_64-linux.nix
          - variant: lto-znver4
            config_file: cachyos-znver4.x86_64-linux.nix
          - variant: server
            config_file: cachyos-server.x86_64-linux.nix
          - variant: hardened
            config_file: cachyos-hardened.x86_64-linux.nix
          - variant: rc
            config_file: cachyos-rc.x86_64-linux.nix
          - variant: lts
            config_file: cachyos-lts.x86_64-linux.nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-build
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          noci-signing-key: ${{ secrets.NOCI_SIGNING_KEY }}
          sandbox-fallback: "false"

      - name: Build kconfigToNix
        run: nix build .#linux_cachyos-${{ matrix.variant }}.kconfigToNix -L --impure

      - name: Diff against checked-in config-nix
        run: diff <(cat result) linux-cachyos/config-nix/${{ matrix.config_file }}
